### ISSUE TITLE
When use realignment_forward.py and realignment_reverse.py should I split bam to forward and reverse by samtools?

### ISSUE THREAD

**Issue by MopingXu** [Zhe-jiang/PRAISE#4]
Sorry to bother you.
I'm curious if I need to divide bam files into positive and negative reads with samtools when use realignment_forward.py and realignment_reverse.py, or I just put bam file to realignment_forward.py and realignment_reverse.py twice?
Best wishes.

**Comment by SoManyPepople** [comment]
I have the same question as you. Please let me know if there is an answer.

**Comment by Zhe-jiang** [comment]
Hi, thank you for being interested in our method and using it. 
It depends on what kind of references you are using. If you are using the sequences of specific genes (transcriptome etc.), you do not need to map the negative reads because there are supposed to be no negative reads. However, if you are using the sequences of the genome, you need to align positive and negative reads separately as you described. Because there could be reads mapping to the negative stand.

**Comment by MopingXu** [comment]
> Hi, thank you for being interested in our method and using it. It depends on what kind of references you are using. If you are using the sequences of specific genes (transcriptome etc.), you do not need to map the negative reads because there are supposed to be no negative reads. However, if you are using the sequences of the genome, you need to align positive and negative reads separately as you described. Because there could be reads mapping to the negative stand.

**Comment by MopingXu** [comment]
> Hi, thank you for being interested in our method and using it. It depends on what kind of references you are using. If you are using the sequences of specific genes (transcriptome etc.), you do not need to map the negative reads because there are supposed to be no negative reads. However, if you are using the sequences of the genome, you need to align positive and negative reads separately as you described. Because there could be reads mapping to the negative stand.

I gei it! Thank you for your reply!!
